webapp/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

		# account/login/
		url(r'^login/$', views.login_user, name='login_user' ),

		# account/register/
		url(r'^register/$', views.register, name='register' ),

		# account/logout/
		url(r'^logout/$', views.logout_user, name='logout_user'),
	]

webapp/forum/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import ListView, DetailView
from forum.models import Question, Answer

app_name = 'forum'

urlpatterns = [

		# for home page
		url(r'^$', views.home, name='home' ),

		# for list of QA forum/
		url(r'^forum/$', views.forum_list , name = 'forum_list'),

		# for detailed Question
		url(r'^forum/(?P<question_id>\d+)/$', views.question_detail , name='question_detail' ),

		# for create question 
		url(r'^forum/add/$', views.create_question , name='create_question' ),

		# for create question 
		url(r'^forum/(?P<question_id>\d+)/answer/$', views.create_answer , name='create_answer' ),

		# for home page
		url(r'^tutorial/$', views.tutorial, name='tutorial' ),

	]

webapp/webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

	# for admin user
    url(r'^admin/', admin.site.urls),

    # for accounts 
    url(r'^account/', include('accounts.urls', namespace = "accounts")),

    # for home page 
    url(r'^', include('forum.urls', namespace = "forum")),
]

webapp/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

webapp/forum/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Question(models.Model):

	user = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=250)
	topic = models.CharField(max_length=100)
	upload_time = models.DateTimeField()
	question_content = models.TextField()
	number_of_views = models.IntegerField(default=0)

	def get_absolute_url(self):
		return reverse('forum:question_detail', kwargs={'question_id':self.pk})

	def __str__(self):
		return self.title

class Answer(models.Model):

	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	user = models.ForeignKey(User, default=1)
	answer_content = models.TextField()
	upload_time = models.DateTimeField() 

	def __str__(self):
		return self.answer_content

webapp/forum/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question, Answer


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['title','topic','question_content']

class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['answer_content']

webapp/accounts/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .models import UserForm

# Create your views here.
# def home(request):
# 	return render(request, 'accounts/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():

        user = form.save(commit=False)

        # cleaned (normalized) data
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'forum/home.html')
    context = {
        "form": form,
    }
    return render(request, 'accounts/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'forum/home.html')
            else:
                return render(request, 'accounts/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'accounts/login.html', {'error_message': 'Invalid login'})
    return render(request, 'accounts/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'accounts/logout.html', context)

webapp/forum/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import Http404
from forum.models import Question, Answer
from .forms import QuestionForm, AnswerForm
import datetime
from django.core.urlresolvers import reverse


# Create your views here.
def home(request):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	return render(request, 'forum/home.html')

def tutorial(request):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	return render(request, 'forum/tutorial.html')
		
def question_detail(request, question_id):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	try:
		question = Question.objects.get(pk=question_id)
		question.number_of_views = question.number_of_views + 1
		question.save()
	except Question.DoesNotExist:
		raise Http404("Question Does Not Exist in the database.")

	return render(request, 'forum/question.html', {'question' : question})

def forum_list(request):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	all_questions = Question.objects.all().order_by("-upload_time")
	context = {'all_questions' : all_questions}
	return render(request, 'forum/forum.html' , context)

def create_question(request):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	form = QuestionForm(request.POST or None)
	if form.is_valid():
		question = form.save(commit=False)
		question.user = request.user
		question.upload_time = datetime.datetime.now()
		question.save()
		return render(request, 'forum/question.html', {'question': question})
	context = {
		"form": form,
	}
	return render(request, 'forum/question_form.html', context)

def create_answer(request, question_id):
	if not request.user.is_authenticated():
		return render(request, 'accounts/login.html')
	form = AnswerForm(request.POST or None)
	try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question Does Not Exist in the database.")
	if form.is_valid():		
		answer = form.save(commit=False)
		answer.question = question
		answer.user = request.user
		answer.upload_time = datetime.datetime.now()
		answer.save()
		# return render(request, 'forum/question.html', {'question': question})
		return render(request, 'forum/question.html', {'question': question})
	context = {
		"form": form,
	}
	return render(request, 'forum/answer_form.html', context)

webapp/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'forum/images/favicon-title.png' %}">
	{% block head %}
	<title>Base</title>
	{% endblock %}
	
</head>
<body>
	{% block body %}
		Base
	{% endblock %}
</body>
</html>

webapp/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block head %}
	<title>Log In</title>
{% endblock %}

{% block body %}
			<div class="card " id="login-dp" >
				<div class="card-header text-center" style="margin-bottom: 25px">
					<div class="card-title" ><h4>LOGIN</h4></div>
				</div>
				<div class="card-block">					
					<form class="form" role="form" method="post" action="{% url 'accounts:login_user'%}" accept-charset="UTF-8" id="login-nav">
						{% csrf_token %}
						{% if error_message %}
                        	<p><strong>{{ error_message }}</strong></p>
                    	{% endif %}
						<div class="input-group" style="margin-bottom: 25px">
			  				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-user"></i></span>
			  				<input type="text" class="form-control" placeholder="Username" name="username" aria-label="Username" aria-describedby="basic-addon1">
						</div>
						<div class="input-group" style="margin-bottom: 25px">
			  				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-lock"></i></span>
			  				<input type="password" class="form-control" placeholder="Password"  name="password" aria-label="Password" aria-describedby="basic-addon1">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary btn-block" style="cursor:pointer">Sign In&emsp;<i class="fa fa-sign-in" aria-hidden="true"></i></button>
						</div>
					</form>
					<div class="bottom text-center">
						<!-- Don't have an account? <a href="{% url 'accounts:register' %}"><b>Join Us</b></a> -->
						New here ? <a href="{% url 'accounts:register' %}"><b>Signup</b></a>	for StudyTonight
					</div>
				</div>
			</div> 
{% endblock %}

webapp/accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block head %}
	<title>Log Out</title>
{% endblock %}

{% block body %}
			<div class="card" id="login-dp" >
				<div class="card-header text-center" >
					<div class="card-title" ><h4>Signed Out</h4></div>
				</div>
				<div class="card-block">					
					<div class="input-group" style="margin-bottom: 25px ; padding: 25px 25px 0;">
						<span class="input-group-addon" id="basic-addon1">You are now signed out.</span>
					</div>
					<div class="bottom text-center">
						<a href="{% url 'accounts:login_user' %}"><b>Click here</b></a> to sign in again.
					</div>
				</div>
			</div> 
{% endblock %}

webapp/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block head %}
	<title>Registration</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-top: 50px;">
	<div class="row">
		<div class="col-4">
		</div>
		<div class="col-4">
			<div class="card" id="register-dp" >
				<div class="card-header text-center">
					<div class="card-title" ><h4>REGISTER</h4></div>
				</div>
				<div class="card-block">					
					<form class="form" role="form" method="post" action="{% url 'accounts:register'%}" accept-charset="UTF-8" id="login-nav">
						{% csrf_token %}
						{% if error_message %}
                        	<p><strong>{{ error_message }}</strong></p>
                    	{% endif %}
                    	<div id="form-element">
	                    	{% for field in form %}
							    <div class="form-group">
							        <div class="col-sm-offset-2 col-sm-10">
							            <span class="text-danger small">{{ field.errors }}</span>
							        </div>
							        <div >
							        	{{ field.label_tag }}
							        </div>
							        <div  >
							        	{{ field }}
							    	</div>
							    </div>
							{% endfor %}
						</div>
						<div class="form-group" >
							<button type="submit" class="btn btn-primary btn-block" style="cursor:pointer">Submit</button>
						</div>
					</form>
					<div class="bottom text-center">
						Already have an account? <br><a href="{% url 'accounts:login_user' %}"><b>Click here</b></a> to log in.
					</div>
				</div>
			</div> 
		</div>
		<div class="col-4">
		</div>
	</div>
</div>
			
{% endblock %}

webapp/forum/templates/forum/answer_form.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Answer the Question</title>
	<style type="text/css">
		.card:hover{
			box-shadow:inset 0 0 10px #000000;
		}
	</style>
{% endblock %}

{% block body %}
<div class="container-fluid" style="margin-top: 10px;">
	<div class="row justify-content-md-center">
		<!-- <div class="col-sm-12 col-md-7"> -->
			<div class="card">
				<div class="card-body">
					<label class="card-title" style="text-decoration: underline;">Write the Solution:</label>
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'forum/form-template.html' %}
						<div class="forum-group">
							<div class="row justify-content-md-center">
								<button type="Submit" class="btn btn-success" style="cursor:pointer">
									Post the Answer
								</button>
							</div>
						</div>
					</form>
						
					
				</div>
			</div>
		<!-- </div> -->
	</div>
</div>
{% endblock %}

webapp/forum/templates/forum/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}">
	<link rel="icon" type="image/png" href="{% static 'forum/images/favicon-title.png' %}">
	{% block head %}
	<title>Base</title>
	{% endblock %}

	<nav class="navbar navbar-dark navbar-expand-lg bg-dark" id="mynav">

			<!-- Logo -->
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'forum:home' %}">
					<span class="nav-heading">
						<i class="fa fa-book" aria-hidden="true"></i>&nbsp;
						StudyTonight
					</span>
				</a>
			</div>

  			<div class="navbar-collapse">
			    <ul class="navbar-nav mr-auto">
			    	<li class="nav-item {% block active_label_tut %}{% endblock %}">
			        	<a class="nav-link" href="{% url 'forum:tutorial' %}">
			        		<i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp; 
			        		Tutorials
			        	</a>
			      	</li>
			      	<li class="nav-item {% block active_label %}{% endblock %}">
			        	<a class="nav-link" href="{% url 'forum:forum_list' %}">
			        		<i class="fa fa-question-circle" aria-hidden="true"></i>&nbsp; 
			        		Q & A Forum
			        	</a>
			      	</li>			      
			    </ul>
			    <ul class="navbar-nav ml-auto">
			    	<li class="nav-item">
			        	<a class="nav-link" href="{% url 'accounts:logout_user' %}">
			        		<i class="fa fa-power-off" aria-hidden="true"></i>&nbsp; 
			        		Logout
			        	</a>
			      	</li>
			    </ul>
			</div>
	</nav>
	
</head>
<body>
	{% block body %}
		Base
	{% endblock %}
	<div class="footer">
      <div class="container">
        <span class="text-muted">
        	© 2017 StudyTonight.  All rights reserved.
        </span>
      </div>
    </div>
</body>
</html>

webapp/forum/templates/forum/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">
				{{field.errors}}
			</span>
		</div>
		<label class="control-label">
			<strong>
			{{ field.label_tag }}
			</strong>
		</label>
		<div class="col-sm-10">
			{{ field }}
		</div>
	</div>
{% endfor%}

webapp/forum/templates/forum/forum.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Q & A Forum</title>
	<style type="text/css">
		.card:hover{
			box-shadow:inset 0 0 10px #000000;
		}
	</style>
	<script>
		window.history.replaceState('Object', 'Title', '/forum/');
	</script>
	
{% endblock %}

{% block active_label %}active{% endblock %}

{% block body %}
	<div class="container-fluid">
    	<div class="row justify-content-md-center" >

    		<div class="col-offset-2 col-8 text-center">
      			<p style='font-size:40px;font-family: "Comic Sans MS", cursive, sans-serif; color: green;'>
      				<i class="fa fa-slideshare" aria-hidden="true"></i>
      				Studyroom
      			</p>
    		</div>
    	</div>

    </div>
	<div class="card">
		<a href="add/" class="btn btn-outline-success btn-lg" role="button" aria-pressed="true">Ask Question </a>
	</div>
		<div class="card" id = "forum_list">
		<div class="card-body" >
			<h4 style="text-decoration: underline;"><i>Already Asked Questions : </i></h4>
		
	
			{% for post in all_questions %}
			<div class="card border-success mb-3" >
				<div class="card-body">
					<div class="float-right" style="color: green;">
	  					<h3 class="text-center">
	  						{{post.answer_set.count}}
	  					</h3>
	  					<p class="darkest-grey" style='font-family: "Comic Sans MS", cursive, sans-serif;'>
	  					<small>
	  						{% if post.answer_set.count > 1 %}
	  							Answers
	  						{% else %}
	  							Answer
	  						{% endif %}
	  					</small>
	  					</p>
	  				</div>
					<div class="float-left">
						{% load staticfiles %}
						<img src="{% static 'forum/images/default-profile.png' %}"  class="rounded-circle img-thumbnail">
					</div>
					<div style="margin-left:75px;">						
					
					<h4 class="card-title">
						<!-- <a href="/forum/{{post.id}}"> -->
						<a href="{% url 'forum:question_detail' post.id %}">
							{{post.title}}
						</a>
					</h4>
					<p class="darkest-grey">
  					<small>
  						<span class="dark-grey">{{ post.upload_time }}</span>&nbsp;&nbsp;&nbsp;by&nbsp;
  						<span>
  							<i class="fa fa-user" aria-hidden="true"></i>  
  							<label>
  								<strong>{{post.user}}</strong>
  							</label>&nbsp;&nbsp;&nbsp;
  						</span>
  						<span title="number of views">
  							<i class="fa fa-eye" aria-hidden="true"></i>
  							{{post.number_of_views}}
  						</span>					
  					</small>
  					</p>
  					
  					<p><span class="badge badge-success">{{post.topic}}</span></p>
					
					</div>
					
					
				</div>
			</div>
			{% endfor %}
		</div>
		</div>
{% endblock %}

webapp/forum/templates/forum/home.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Home</title>
  <script>
    window.history.replaceState('Object', 'Title', '/');
  </script>
{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container">
    <div class="container-fluid" style="padding: 30px;">
    	<div class="row justify-content-md-center" style="margin-top: 100px;margin-bottom: 100px;">
    		<div class="col-4">
    		<a target="_blank" href="{% static 'forum/images/study5.jpg' %}">
      			<img src="{% static 'forum/images/study5.jpg' %}" style="" id ="home_image">
      		</a>
      		</div>
    		<div class="col-offset-2 col-8 text-center">
      			<p style='font-size:40px;font-family: "Comic Sans MS", cursive, sans-serif; color: green;'>Education simplified</p><p>
      			</p><p style="font-size:16px;">Our mission is to empower young Students to be the inventors and creators.</p>
      			<br><p> <a href="{% url 'forum:tutorial' %}" class="btn btn-success">Start Learning Today →</a> </p>
    		</div>
    	</div>
    	<div class="row justify-content-md-center" style="margin-top: 100px;margin-bottom: 100px;">
    		<div class="col-offset-2 col-8 text-center">
      			<p style='font-size:40px;font-family: "Comic Sans MS", cursive, sans-serif; color: green;'>Studyroom</p><p>
      			</p><p style="font-size:16px;">We're a community of Students sharing knowledge by asking Questions and answering them in our space.</p>
      			<br><p> <a href="{% url 'forum:forum_list' %}" class="btn btn-success">Start Studyroom Learning Today →</a> </p>
    		</div>
    		<div class="col-4">
    		<a target="_blank" href="{% static 'forum/images/study6.jpg' %}">
      			<img src="{% static 'forum/images/study6.jpg' %}" style="" id ="home_image">
      		</a>
      		</div>
    	</div>

    </div>
</div>
{% endblock %}

webapp/forum/templates/forum/question.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Question</title>
	<style type="text/css">
		.card:hover{
			box-shadow:inset 0 0 10px #000000;
		}
	</style>
	<script>
		window.history.replaceState('Object', 'Title', '/forum/{{question.id}}/');
	</script>
{% endblock %}

{% block body %}
	
	<div class="card" id = "forum_list">
		<div class="card-body" >
			<div class="card border-success mb-3" >
				<div class="card-body">
					<div class="float-left">
						{% load staticfiles %}
						<img src="{% static 'forum/images/default-profile.png' %}"  class="rounded-circle img-thumbnail">
					</div>
					<div style="margin-left:75px;">	
					<h3 class="varela card-title" style='font-family: "Comic Sans MS", cursive, sans-serif;'>{{question.title}}</h3>
					<p class="varela darkest-grey">
						<small>
							<span class="dark-grey">{{question.upload_time}}</span>&nbsp;&nbsp;&nbsp;by&nbsp;
	  						<span>
	  							<i class="fa fa-user" aria-hidden="true"></i>  
	  							<label>
	  								<strong>{{question.user}}</strong>
	  							</label>&nbsp;&nbsp;&nbsp;
	  						</span>
	  						<span>
	  							<i class="fa fa-eye" aria-hidden="true"></i>
	  							{{question.number_of_views}}
	  						</span>
						</small>
					</p>

					<div style="font-family:Tahoma, Geneva, sans-serif">
						{{question.question_content|safe|linebreaks}}
					</div>
					<p><span class="badge badge-success">{{question.topic}}</span></p>
					</div>
				</div>
			</div>
			
			<!-- <h4> Answers : </h4> -->
			

			<div class="card border-success mb-3">
			  <div class="card-header bg-transparent border-success" style='font-family: "Comic Sans MS", cursive, sans-serif;'>Answers :</div>
			  <div class="card-body">
			  	{% if question.answer_set.all %}
				  	{% for answer in question.answer_set.all %}
				  		<div class="card border-success mb-3">
				  			<div class="card-body">
				  				<div class="float-left">
									{% load staticfiles %}
									<img src="{% static 'forum/images/default-profile.png' %}"  class="rounded-circle img-thumbnail">
								</div>
								<div style="margin-left:75px;">	
				  				<span>
		  							<i class="fa fa-user" aria-hidden="true"></i>  
		  							<label>
		  								<strong>{{answer.user}}</strong>
		  							</label>
		  						</span>	<br>			  			
								<span style="font-family:Tahoma, Geneva, sans-serif" class="text-secondary">{{answer.answer_content|safe|linebreaks}} </span> <br>
								<small>{{answer.upload_time}}</small>
								</div>
							</div>
				  		</div>
						
					{% endfor %}
				{% else %}
					<p align="center">No Answer given yet.</p>
				{% endif %}
			  </div>
			  <div class="card-footer bg-transparent border-success ">
			  	<div class="row justify-content-md-center">
			  		<a href="answer/" class="btn btn-outline-success btn-lg" role="button" aria-pressed="true">Answer the Question</a>
			  	</div>
			  </div>
			</div>
		</div>
	</div>
	
{% endblock %}

webapp/forum/templates/forum/question_form.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Ask a Question</title>
	<style type="text/css">
		.card:hover{
			box-shadow:inset 0 0 10px #000000;
		}
	</style>
{% endblock %}

{% block body %}
<div class="container-fluid" style="margin-top: 10px;">
	<div class="row justify-content-md-center">
		<!-- <div class="col-sm-12 col-md-7"> -->
			<div class="card">
				<div class="card-body">
					<label class="card-title" style="text-decoration: underline;">Fill the form to ask the question:</label>

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'forum/form-template.html' %}
						<div class="forum-group">
							<div class="row justify-content-md-center">
								<button type="Submit" class="btn btn-success" style="cursor:pointer">
									Post the Question
								</button>
							</div>
						</div>
					</form>
						
					
				</div>
			</div>
		<!-- </div> -->
	</div>
</div>
{% endblock %}

webapp/forum/templates/forum/tutorial.html
{% extends 'forum/base.html' %}

{% block head %}
	<title>Tutorials</title>
	{% load staticfiles %}
 {% endblock %}

{% block active_label_tut %}active{% endblock %}

{% block body %}
<div class="container">
	
    <div class="container-fluid">
    	<div class="row justify-content-md-center" >

    		<div class="col-offset-2 col-8 text-center">
      			<p style='font-size:40px;font-family: "Comic Sans MS", cursive, sans-serif; color: green;'>
      				<i class="fa fa-book" aria-hidden="true"></i>
      				StudyTonight Library
      			</p>
      			<a target="_blank" href="{% static 'forum/images/study3.jpg' %}">
      			<img src="{% static 'forum/images/study3.jpg' %}" style="" id ="tut_image">
      			</a>
    		</div>
    	</div>

    </div>
    <div class="container-fluid" id="course">
    	<div class="row">
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">CORE JAVA →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">DBMS →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">DATA STRUCTURE →</p>
    				</div>
    			</div>
    		</div>
    	</div>
    	<div class="row">
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">C LANGUAGE →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">C++ →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">OPERATING SYSTEMS →</p>
    				</div>
    			</div>
    		</div>
    	</div>
    	<div class="row">
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">PYTHON →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">COMPUTER NETWORKS →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">JSP →</p>
    				</div>
    			</div>
    		</div>
    	</div>
    	<div class="row">
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">CSS →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">GITHUB →</p>
    				</div>
    			</div>
    		</div>
    		<div class="col-4" style="padding: 20px;">
    			<div class="card" style="width: 20rem;cursor:not-allowed;">
    				<div class="card-body">
    					<p class="text-center card-title">COMPUTER ARCHITECHTURE →</p>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
{% endblock %}